# Use a Node.js base image with a compatible version (v18 or higher)
FROM node:18

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json package-lock.json /app/
RUN npm install

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Copy source code
COPY . /app

# Run Angular tests
CMD ["ng", "test", "--watch=false", "--no-progress"]
