# Use a lightweight Python image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy source code and test requirements
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run tests
CMD ["flake8", "."]
