name: CI/CD Pipeline for Coding Challenges Platform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Step 1: Backend Build and Test
  backend:
    name: Backend Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name:  List Root Directory
        run: ls -al

      - name:  List Backend Directory
        run: ls -al coding-challenges-platform/Backend

      - name: Build backend Docker image for testing
        run: |
          docker build -t backend-test-image:latest -f coding-challenges-platform/Backend/Dockerfile.test coding-challenges-platform/Backend

      - name: Run backend static code analysis
        run: |
          docker run --rm backend-test-image:latest

  # Step 2: Frontend Build and Test
  frontend:
    name: Frontend Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name:  List Root Directory
        run: ls -al

      - name: List Frontend Directory
        run: ls -al coding-challenges-platform

      - name: Build frontend Docker image for testing
        run: |
          docker build -t frontend-test-image:latest -f coding-challenges-platform/Dockerfile.test coding-challenges-platform

      - name: Run frontend tests inside Docker container
        run: |
          docker run --rm frontend-test-image:latest npm test -- --watch=false --no-progress
