name: CI/CD Pipeline for Coding Challenges Platform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Backend Build and Test
  backend:
    name: Backend Build and Test (Docker)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build backend Docker image for testing
        working-directory: ./Backend
        run: |
          docker build -t backend-test-image:latest -f Dockerfile.test .

      - name: Run backend tests inside Docker container
        working-directory: ./Backend
        run: |
          docker run --rm backend-test-image:latest pytest

  # Frontend Build and Test
  frontend:
    name: Frontend Build and Test (Docker)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build frontend Docker image for testing
        run: |
          docker build -t frontend-test-image:latest -f Dockerfile.test .

      - name: Run frontend tests inside Docker container
        run: |
          docker run --rm frontend-test-image:latest npm test -- --watch=false --no-progress

  # Simulate Deployment
  simulate-deploy:
    name: Simulate Deployment
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build backend Docker image for deployment
        working-directory: ./Backend
        run: |
          docker build -t backend-deploy-image:latest .

      - name: Build frontend Docker image for deployment
        run: |
          docker build -t frontend-deploy-image:latest .

      - name: Simulate running containers
        run: |
          # Start backend container
          docker run -d --name simulate-backend -p 8000:8000 backend-deploy-image:latest

          # Start frontend container
          docker run -d --name simulate-frontend -p 8080:80 frontend-deploy-image:latest

          # Check running containers
          docker ps

          # Stop and remove containers after simulation
          docker stop simulate-backend simulate-frontend
          docker rm simulate-backend simulate-frontend
